"""v2 signing — cross-language parity against the contracts' own committed vectors.

`tests/vectors/signing-v3.json` is generated by
`vorq-evm-contracts/test/Vectors.t.sol`, which reproduces the devnet's
deterministic deployment in-process, derives each digest from the case's own
published EIP-712 payload, and hands every signature to the deployed contract,
which must accept it before a byte is written. So it is the authority this Python
signer is checked against, and nothing here restates a digest, a separator or a
type table on the page: every expected value is read out of the file.

The one thing the file cannot check is *which deployment* a signer thinks it is
signing for, because a wrong `verifyingContract` produces a signature that
recovers to a stranger rather than an error. `TestDomainSeparation` is that
check, built from the file's own registry addresses.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from eth_account import Account
from eth_account.messages import encode_typed_data
from eth_utils import keccak

from vorq._crypto import (
    CANCEL_TYPES,
    ORDER_TYPES,
    RECEIVE_AUTHORIZATION_TYPES,
    SESSION_TYPES,
    WalletSigner,
    content_job_id,
    vorq_domain,
)
from vorq._terms import (
    CONTRACT_FIELDS,
    ChainContext,
    OrderTerms,
    TokenDomain,
    order_domain,
    payment_domain,
    registry_domain,
)
from vorq.errors import ValidationError

from .vectors import ADDRESSES, CASES, DOMAINS, VECTORS, local_types, message

#: The payment token's own EIP-712 name and version, as the file publishes them.
#: They differ per network, which is why the node states them rather than the SDK.
TOKEN = DOMAINS["payment_token"]["domain"]

#: The chain context those vectors belong to, built from the file's own
#: `addresses` block — including `ask_registry`, which this SDK signs nothing
#: against but must carry so a mix-up is statable rather than invisible.
CTX = ChainContext(
    chain_id=VECTORS["chain_id"],
    job_registry=ADDRESSES["job_registry"],
    provider_registry=ADDRESSES["provider_registry"],
    ask_registry=ADDRESSES["ask_registry"],
    usdc=ADDRESSES["payment_token"],
    decimals=6,
    token_domain=TokenDomain(TOKEN["name"], TOKEN["version"]),
)

#: The vectors' own client wallet — anvil index 4. Which key signs is free for
#: the orders, the cancel and the session, where recovery only has to return
#: *this* address. It is not free for `payment-authorization`: `from` is a signed
#: member, so only the wallet the vector names there reaches its digest at all.
VECTOR_KEY = "0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a"


def raw(name: str) -> dict:
    """A case's message exactly as the file carries it, before any decoding."""
    return CASES[name]["typed_data"]["message"]


def extra(name: str) -> dict:
    return CASES[name]["extra"]


def _b(value: str) -> bytes:
    return bytes.fromhex(value[2:] if value.startswith("0x") else value)


def _terms_of(name: str) -> OrderTerms:
    m = raw(name)
    return OrderTerms(
        c=_b(m["c"]),
        model_id=m["modelId"],
        sla_secs=m["slaSecs"],
        rate_in=int(m["rateIn"]),
        rate_out=int(m["rateOut"]),
        units_in=m["unitsIn"],
        units_out=m["unitsOut"],
        designated=m["designated"],
        expires_at=m["expiresAt"],
    )


def _digest(domain: dict, types: dict, msg: dict) -> str:
    """The EIP-712 digest eth-account would sign, as 0x hex."""
    signable = encode_typed_data(domain, types, msg)
    return "0x" + keccak(b"\x19" + signable.version + signable.header + signable.body).hex()


def recover_against_vector(name: str, signature: str) -> str:
    """Recover ``signature`` using the **vector's own** published payload.

    A digest this SDK built differently — a renamed member, a reordered table, a
    `version` dropped from the token's domain — recovers a different address
    rather than raising, which is the whole failure mode the file exists to
    catch. Rebuilding the payload from `vorq/` here instead would prove only
    that this test and that module agree with each other.
    """
    case = CASES[name]["typed_data"]
    return Account.recover_message(
        encode_typed_data(case["domain"], local_types(name), message(name)),
        signature=signature,
    )


# -- the chain context ---------------------------------------------------------


class TestChainContext:
    """Q6: all four contracts, and the fourth is the one that bites."""

    WIRE = {
        "chain_id": VECTORS["chain_id"],
        "contracts": {
            "job_registry": ADDRESSES["job_registry"],
            "provider_registry": ADDRESSES["provider_registry"],
            "ask_registry": ADDRESSES["ask_registry"],
            "usdc": ADDRESSES["payment_token"],
        },
        "decimals": 6,
        "token_domain": {"name": TOKEN["name"], "version": TOKEN["version"]},
        # On the body and deliberately unread: this SDK does not price gas, does
        # not wait on a head, and assembles no transaction (Q19).
        "head_block": 128,
        "block_time_ms": 1000,
        "fee_bps": 100,
    }

    def test_it_carries_all_four_addresses(self):
        ctx = ChainContext.from_wire(self.WIRE)
        assert ctx.contracts == self.WIRE["contracts"]
        assert set(ctx.contracts) == set(CONTRACT_FIELDS)
        assert CONTRACT_FIELDS == (
            "job_registry", "provider_registry", "ask_registry", "usdc"
        )

    def test_it_carries_the_tokens_decimals_and_its_own_domain(self):
        """Both are the node's to state: they differ per network, and the second
        is signed over — a wrong `version` recovers to a stranger."""
        ctx = ChainContext.from_wire(self.WIRE)
        assert ctx.decimals == 6
        assert ctx.token_domain == TokenDomain(TOKEN["name"], TOKEN["version"])

    @pytest.mark.parametrize("missing", ["decimals", "token_domain"])
    def test_a_body_without_the_token_is_refused(self, missing):
        wire = {k: v for k, v in self.WIRE.items() if k != missing}
        with pytest.raises(ValidationError, match=missing):
            ChainContext.from_wire(wire)

    @pytest.mark.parametrize("domain", [{"name": "USDC"}, {"name": "", "version": "2"},
                                        {"name": "USDC", "version": ""}, "USDC"])
    def test_a_half_stated_token_domain_is_refused(self, domain):
        """Half a domain is worse than none: it signs, and it recovers to nobody."""
        with pytest.raises(ValidationError, match="token_domain"):
            ChainContext.from_wire({**self.WIRE, "token_domain": domain})

    @pytest.mark.parametrize(
        "missing",
        ["job_registry", "provider_registry", "ask_registry", "usdc"],
    )
    def test_a_missing_contract_is_refused_by_name(self, missing):
        wire = {**self.WIRE, "contracts": {
            k: v for k, v in self.WIRE["contracts"].items() if k != missing
        }}
        with pytest.raises(ValidationError, match=missing):
            ChainContext.from_wire(wire)

    def test_provider_registry_is_carried_even_though_this_sdk_signs_no_registry_op(self):
        """It is the address the plan's own type dropped (Q6).

        Nothing in the client signs a ProviderRegistry op — but the VORQ domains
        are otherwise identical, so a context without it cannot state the
        difference, and a consumer that guessed would produce a signature that
        recovers to somebody else instead of failing.
        """
        ctx = ChainContext.from_wire(self.WIRE)
        assert ctx.provider_registry == ADDRESSES["provider_registry"]
        assert ctx.provider_registry != ctx.job_registry

    def test_it_is_frozen(self):
        ctx = ChainContext.from_wire(self.WIRE)
        with pytest.raises(Exception):
            ctx.job_registry = ADDRESSES["payment_token"]  # type: ignore[misc]

    def test_a_body_with_no_contracts_block_is_refused(self):
        with pytest.raises(ValidationError):
            ChainContext.from_wire({"chain_id": VECTORS["chain_id"]})

    def test_a_malformed_address_is_refused_by_name(self):
        wire = {**self.WIRE, "contracts": {**self.WIRE["contracts"], "usdc": "0xdead"}}
        with pytest.raises(ValidationError, match="usdc"):
            ChainContext.from_wire(wire)


# -- the type tables are the contracts' ----------------------------------------


class TestTypeTables:
    """Direct list equality against the published tables.

    The file carries the actual `[{name, type}, ...]` tables the contract's own
    accepted signatures were built from — not a derived type string — so an SDK
    table that disagrees is caught here without rebuilding a string to compare.
    """

    def test_the_order_table_is_the_one_the_contract_verifies(self):
        assert ORDER_TYPES == local_types("order-designated")

    def test_the_cancel_table_is_the_one_the_contract_verifies(self):
        assert CANCEL_TYPES == local_types("cancel")

    def test_the_authorization_table_is_the_one_the_token_verifies(self):
        assert RECEIVE_AUTHORIZATION_TYPES == local_types("payment-authorization")

    def test_the_session_table_matches(self):
        """No contract verifies a session, so this file and the coordinator are the
        only two places it exists — which is exactly why it needs a vector."""
        assert SESSION_TYPES == local_types("session")

    def test_no_signed_table_carries_a_cid(self):
        for table in (ORDER_TYPES, CANCEL_TYPES):
            for members in table.values():
                assert not [f for f in members if "cid" in f["name"].lower()]


# -- domain separation, the failure that is silent -----------------------------


class TestDomainSeparation:
    """Q6: the registries' domains, and what keeps them apart."""

    def test_the_two_domains_differ_in_name_as_well_as_address(self):
        """The registries used to share the name `VORQ` and differ only in
        `verifyingContract`. That left one real failure invisible: a context whose
        two address slots resolved to the same contract produced digests
        indistinguishable from legitimate ones. Distinct names close it.
        """
        job, reg = order_domain(CTX), registry_domain(CTX)
        assert job["name"] == "VORQ Jobs"
        assert reg["name"] == "VORQ Providers"
        assert job["version"] == reg["version"] == "2"
        assert job["chainId"] == reg["chainId"] == CTX.chain_id
        assert job["verifyingContract"] != reg["verifyingContract"]
        assert {k for k in job} == {k for k in reg}

    def test_the_names_alone_separate_them_even_at_one_address(self):
        """Hold the address constant and the digests must still diverge — that is
        what makes the separation independent of configuration being right."""
        collapsed = ChainContext(
            chain_id=CTX.chain_id,
            job_registry=CTX.job_registry,
            provider_registry=CTX.job_registry,  # the misconfiguration in question
            ask_registry=CTX.ask_registry,
            usdc=CTX.usdc,
            decimals=CTX.decimals,
            token_domain=CTX.token_domain,
        )
        assert order_domain(collapsed) != registry_domain(collapsed)
        msg = _terms_of("order-designated").message()
        assert _digest(order_domain(collapsed), ORDER_TYPES, msg) != _digest(
            registry_domain(collapsed), ORDER_TYPES, msg
        )

    def test_the_domain_is_the_one_the_vector_records(self):
        assert order_domain(CTX) == CASES["order-designated"]["typed_data"]["domain"]

    def test_one_struct_hash_under_the_two_domains_gives_two_digests(self):
        """The whole of the silent-failure argument, as arithmetic."""
        msg = _terms_of("order-designated").message()
        assert _digest(order_domain(CTX), ORDER_TYPES, msg) == CASES["order-designated"]["digest"]
        assert _digest(registry_domain(CTX), ORDER_TYPES, msg) != CASES["order-designated"]["digest"]

    def test_a_signature_under_the_wrong_domain_recovers_to_a_stranger(self):
        """Not an error — a different address. That is why the context is explicit."""
        terms = _terms_of("order-designated")
        msg = terms.message()
        wrong = encode_typed_data(registry_domain(CTX), ORDER_TYPES, msg)
        signer = WalletSigner(Account.create().key.hex())
        signature = signer.sign_order_v2(terms, CTX)
        assert Account.recover_message(
            encode_typed_data(order_domain(CTX), ORDER_TYPES, msg), signature=signature
        ) == signer.address
        assert Account.recover_message(wrong, signature=signature) != signer.address

    def test_the_payment_domain_is_the_tokens_own_four_members(self):
        d = payment_domain(CTX)
        assert set(d) == {"name", "version", "chainId", "verifyingContract"}
        assert d == CASES["payment-authorization"]["typed_data"]["domain"]

    def test_every_on_chain_domain_records_the_separator_it_was_built_under(self):
        for key in ("job_registry", "provider_registry", "ask_registry", "payment_token"):
            assert DOMAINS[key]["separator"].startswith("0x")

    def test_the_off_chain_domains_name_no_contract(self):
        """A session has no verifying contract at all — three domain members, not
        four — and the file says so with a null separator rather than a zero word."""
        for key in ("escrow", "session"):
            assert DOMAINS[key]["separator"] is None
            assert "verifyingContract" not in DOMAINS[key]["domain"]


# -- Order ---------------------------------------------------------------------


@pytest.mark.parametrize("name", ["order-designated", "order-open"])
class TestOrderVectors:
    def test_the_digest_matches_the_contracts_own(self, name):
        assert _digest(order_domain(CTX), ORDER_TYPES, _terms_of(name).message()) == (
            CASES[name]["digest"]
        )

    def test_the_signature_recovers_to_the_vectors_signer(self, name):
        signable = encode_typed_data(order_domain(CTX), ORDER_TYPES, _terms_of(name).message())
        assert Account.recover_message(signable, signature=CASES[name]["signature"]) == (
            CASES[name]["signer"]
        )

    def test_the_job_id_is_keccak_of_owner_and_c_with_no_inner_hash(self, name):
        assert content_job_id(extra(name)["owner"], _b(raw(name)["c"])) == extra(name)["job_id"]

    def test_the_wire_terms_name_no_cid_of_any_kind(self, name):
        """Asserted on **parsed keys**, never on a substring of the body.

        A container is base64 and base64 of random bytes contains most short
        strings often enough to fail a run nobody can reproduce.
        """
        wire = _terms_of(name).to_wire(
            owner=extra(name)["owner"],
            job_id=extra(name)["job_id"],
            signature=CASES[name]["signature"],
            decimals=6,
        )
        assert not [k for k in wire if "cid" in k.lower()]
        assert set(wire) == {
            "c", "owner", "job_id", "model_id", "sla_secs", "rate_in", "rate_out",
            "units_in", "units_out", "designated", "expires_at", "signature",
        }


class TestTaskCidIsNotSigned:
    def test_a_task_cid_folded_into_the_struct_would_fail_this(self):
        """The one case that catches it, and it is deliberate (`order-designated`).

        The vector carries a `task_cid` beside the message precisely so an
        implementation that signs it produces a different digest here.
        """
        assert extra("order-designated")["task_cid"]
        widened = {**ORDER_TYPES, "Order": [
            *ORDER_TYPES["Order"], {"name": "taskCid", "type": "bytes"},
        ]}
        msg = {
            **_terms_of("order-designated").message(),
            "taskCid": _b(extra("order-designated")["task_cid"]),
        }
        assert _digest(order_domain(CTX), widened, msg) != CASES["order-designated"]["digest"]

    def test_the_published_table_names_no_task_cid(self):
        assert "taskCid" not in {f["name"] for f in local_types("order-designated")["Order"]}


class TestOpenOrderSentinel:
    """Q22: `designated` is 0 for an open order, never a null."""

    def test_the_open_vector_designates_zero(self):
        assert raw("order-open")["designated"] == 0

    def test_zero_is_signable_and_none_is_not(self):
        assert _digest(order_domain(CTX), ORDER_TYPES, _terms_of("order-open").message()) == (
            CASES["order-open"]["digest"]
        )
        with pytest.raises(ValidationError):
            OrderTerms(**{**_terms_of("order-open").__dict__, "designated": None})  # type: ignore[arg-type]


class TestRateWire:
    """The terms hold atomic rates (what is signed); the wire carries them as USD strings."""

    @pytest.mark.parametrize("field", ["rate_in", "rate_out"])
    def test_past_uint128_is_refused(self, field):
        with pytest.raises(ValidationError, match=f"vorq.{field} must be an integer in"):
            OrderTerms(**{**_terms_of("order-open").__dict__, field: 2**128})

    def test_rates_go_out_as_canonical_usd_strings(self):
        terms = OrderTerms(**{**_terms_of("order-open").__dict__,
                              "rate_in": 50_000, "rate_out": 2**128 - 1})
        wire = terms.to_wire(owner="0x" + "11" * 20, job_id="0x" + "22" * 32, signature="0x",
                             decimals=6)
        assert wire["rate_in"] == "0.05"
        assert wire["rate_out"] == "340282366920938463463374607431768.211455"
        assert type(wire["model_id"]) is int and type(wire["expires_at"]) is int


# -- Cancel --------------------------------------------------------------------


class TestCancelVector:
    def test_the_digest_matches(self):
        assert _digest(order_domain(CTX), CANCEL_TYPES, message("cancel")) == CASES["cancel"]["digest"]

    def test_the_signature_recovers_to_the_vectors_signer(self):
        signable = encode_typed_data(order_domain(CTX), CANCEL_TYPES, message("cancel"))
        assert Account.recover_message(signable, signature=CASES["cancel"]["signature"]) == (
            CASES["cancel"]["signer"]
        )

    def test_sign_cancel_round_trips(self):
        signer = WalletSigner(Account.create().key.hex())
        sig = signer.sign_cancel(raw("cancel")["jobId"], raw("cancel")["issuedAt"], CTX)
        signable = encode_typed_data(order_domain(CTX), CANCEL_TYPES, message("cancel"))
        assert Account.recover_message(signable, signature=sig) == signer.address

    def test_it_cancels_the_row_the_order_vector_posted(self):
        assert raw("cancel")["jobId"] == extra("order-designated")["job_id"]


# -- the payment authorization -------------------------------------------------


class TestPaymentAuthorizationVector:
    def test_the_digest_matches_the_tokens_own(self):
        assert _digest(
            payment_domain(CTX), RECEIVE_AUTHORIZATION_TYPES, message("payment-authorization")
        ) == CASES["payment-authorization"]["digest"]

    def test_the_signature_recovers_to_the_vectors_signer(self):
        signable = encode_typed_data(
            payment_domain(CTX), RECEIVE_AUTHORIZATION_TYPES, message("payment-authorization")
        )
        assert Account.recover_message(
            signable, signature=CASES["payment-authorization"]["signature"]
        ) == CASES["payment-authorization"]["signer"]

    def test_sign_payment_authorization_lands_on_the_vector(self):
        """The SDK's own entry point, not a hand-built message."""
        signer = WalletSigner(VECTOR_KEY)
        m, r = message("payment-authorization"), raw("payment-authorization")
        sig = signer.sign_payment_authorization(
            amount=int(m["value"]), job_id=r["nonce"],
            expires_at=int(m["validBefore"]) - 1, ctx=CTX,
        )
        assert recover_against_vector("payment-authorization", sig) == signer.address
        # `from` is signed, so exactly one wallet reaches this digest — which is
        # what the assertion above is worth only if this holds.
        assert r["from"] == signer.address

    def test_the_nonce_is_the_job_id_and_is_not_chosen_here(self):
        """One authorization per job: the token's own nonce table makes it
        single-use, and only the payee can execute it, so an authorization for
        another job or another payee funds nothing here."""
        m, r = message("payment-authorization"), raw("payment-authorization")
        assert r["nonce"] == extra("payment-authorization")["job_id"]
        assert r["to"] == CTX.job_registry
        assert m["validAfter"] == 0

    def test_the_window_is_the_orders_own_plus_one_second(self):
        """The token requires `now < validBefore` and a claim may land exactly on
        `expires_at`, so the authorization is open one second longer."""
        signer = WalletSigner(VECTOR_KEY)
        m, r = message("payment-authorization"), raw("payment-authorization")
        args = dict(amount=int(m["value"]), job_id=r["nonce"], ctx=CTX)
        assert signer.sign_payment_authorization(
            expires_at=int(m["validBefore"]) - 1, **args
        ) != signer.sign_payment_authorization(expires_at=int(m["validBefore"]), **args)

    def test_the_amount_is_the_one_claim_will_pull(self):
        assert int(raw("payment-authorization")["value"]) == int(
            extra("payment-authorization")["amount"]
        )


# -- the session handshake -----------------------------------------------------


class TestSessionVector:
    """The off-chain auth artifact — no contract, three spellings across the repos.
    Its `chainId` is the deployment's, announced by `GET /auth/nonce`: a browser
    wallet only signs a typed-data domain on the chain it is switched to, so the
    old pin at 1 locked every real wallet out. A session is still never submitted
    anywhere, and the coordinator verifies it against a nonce minted in its own
    database, which is what prevents replay. Version `1` and a domain with no
    `verifyingContract` keep it in a namespace the chain will never accept, so a
    captured login can never be replayed as an op.
    """

    def test_the_domain_is_bound_to_the_vectors_chain(self):
        domain = CASES["session"]["typed_data"]["domain"]
        assert vorq_domain(VECTORS["chain_id"]) == domain
        assert domain["chainId"] == VECTORS["chain_id"]
        assert domain["version"] == "1"
        assert "verifyingContract" not in domain

    def test_the_digest_matches(self):
        assert _digest(vorq_domain(VECTORS["chain_id"]), SESSION_TYPES, message("session")) == CASES["session"]["digest"]

    def test_the_signature_recovers_to_the_vectors_signer(self):
        signable = encode_typed_data(vorq_domain(VECTORS["chain_id"]), SESSION_TYPES, message("session"))
        assert Account.recover_message(signable, signature=CASES["session"]["signature"]) == (
            CASES["session"]["signer"]
        )

    def test_sign_nonce_round_trips(self):
        signer = WalletSigner(Account.create().key.hex())
        sig = signer.sign_nonce(raw("session")["nonce"], VECTORS["chain_id"])
        signable = encode_typed_data(
            vorq_domain(VECTORS["chain_id"]), SESSION_TYPES, {"address": signer.address, "nonce": raw("session")["nonce"]}
        )
        assert Account.recover_message(signable, signature=sig) == signer.address

    def test_the_session_domain_is_not_an_op_domain(self):
        """Version 1 against the ops' version 2, so the two namespaces cannot meet."""
        assert vorq_domain(CTX.chain_id)["version"] != order_domain(CTX)["version"]


class TestTheVectorsBelongToThisDeployment:
    def test_the_file_says_which_chain_it_is_for(self):
        assert VECTORS["chain_id"] == CTX.chain_id

    def test_the_addresses_are_the_ones_every_digest_was_built_over(self):
        assert order_domain(CTX)["verifyingContract"] == ADDRESSES["job_registry"]
        assert payment_domain(CTX)["verifyingContract"] == ADDRESSES["payment_token"]

    def test_the_c_values_are_the_containers(self):
        """The vectors' `c` values are lifted from `container-v1.json` (Q14).

        A container test and an order test therefore chain end to end rather than
        starting from an invented commitment.
        """
        containers = json.loads(
            (Path(__file__).parent / "vectors" / "container-v1.json").read_text()
        )
        known = {case["c"].lower() for case in containers["cases"]}
        for name in ("order-designated", "order-open"):
            assert raw(name)["c"].lower() in known
