"""Client-side cryptography: EIP-712 signing and sealed-box sealing.

The ``Signer`` and ``Cipher`` protocols are the stable surface; ``WalletSigner``
and ``SealedBoxCipher`` are the implementations the SDK ships.

- ``WalletSigner`` holds the Inference Wallet Key (a secp256k1 private key) and
  produces **EIP-712** signatures. There are two worlds of them and they are
  deliberately separate. The **chain** signatures — ``Order``, ``Cancel``, and the
  payment token's ``ReceiveWithAuthorization`` — are verified by deployed contracts, so
  they carry a ``verifyingContract`` and belong to one deployment; that
  deployment arrives as a :class:`~vorq._terms.ChainContext` and is never
  defaulted, because a signature under the wrong one recovers to a stranger
  rather than failing. The **off-chain** signature — the session handshake — is
  verified by a coordinator and belongs to no contract, so it keeps its own
  domain and has no ``verifyingContract`` at all. A captured login must not be an
  order, and an order must not be a login.
- ``SealedBoxCipher`` seals payloads to a recipient's Curve25519 public key with
  libsodium sealed boxes (anonymous sender, authenticated recipient) and opens
  boxes addressed to its own key. ``derive_result_cipher`` builds one straight
  from the wallet, so the key that results are sealed back to needs no storage.

**Every signature this module produces is canonical: ``v`` in {27, 28} and
``s <= N/2``, and there is a test that says so.** The contracts recover with bare
``ecrecover`` and impose no canonical-``s`` bound, so the high-``s`` twin
``(r, N - s, 55 - v)`` of any signature here recovers the same address and is
accepted just as readily — signature **malleability**, deliberate on the chain
side and harmless there, because nothing on this network keys on signature
bytes: replay is stopped by the job state machine and by the monotonic
``issuedAt`` floors (see ``vorq-evm-contracts/README.md``, "Signature caveats").

The obligation that leaves on this side is narrow and absolute: **a signature is
never an identifier.** Not a cache key, not a dedupe key, not an idempotency
key, not a job id — two byte strings that are not equal can carry exactly the
same authority, and any code that counted them would count one authorization
twice. ``eth-account`` emits low-``s`` today; the test is what keeps that a
property of this SDK rather than of a dependency version.
"""

from __future__ import annotations

import os
import re
from typing import Any, Protocol, runtime_checkable

from eth_account import Account
from eth_account.messages import encode_defunct
from eth_utils import keccak, to_bytes
from nacl.encoding import HexEncoder
from nacl.public import PrivateKey, PublicKey, SealedBox

from ._terms import ChainContext, OrderTerms, order_domain, payment_domain

# -- canonical EIP-712 contract -------------------------------------------------
#
# Single source of truth for what a contract verifies. Changing any name or type
# here changes the signatures on the wire, and the vectors in
# `tests/vectors/signing-v3.json` — generated by the contracts themselves — are
# what says so out loud.

#: The off-chain domain: the session handshake, and nothing else. Version ``1``
#: against the on-chain artifacts' ``2``, with no ``verifyingContract`` at all,
#: keeps it in a namespace the chain will never accept — so a captured login can
#: never be replayed as an op.
DOMAIN_NAME = "VORQ Session"
DOMAIN_VERSION = "1"

#: The session handshake's chain id is the deployment's, announced by ``GET
#: /auth/nonce`` as ``chain_id``. It used to be pinned at 1: a browser wallet
#: refuses to sign a typed-data domain whose chain is not the one it is on, so
#: the pin locked every real wallet out, and every SDK moved together.

#: ``Order`` — the contract's own type, member for member, at the contract's own
#: widths. The type string this produces is
#: ``Order(bytes32 c,uint32 modelId,uint32 slaSecs,uint128 rateIn,uint128
#: rateOut,uint32 unitsIn,uint32 unitsOut,uint32 designated,uint64 expiresAt)``.
#:
#: **There is no ``taskCid`` member.** The contract stores one on the row and
#: does not hash it, because the coordinator mints the name when it pins and the
#: client cannot know it at signing time. There is no job id either — the chain
#: derives that from the recovered signer and ``c`` — and no result key, which
#: travels sealed inside the payload. `signing-v3.json`'s `order-designated` case
#: carries a `task_cid` beside the message for exactly this reason: an
#: implementation that folds it in fails there and nowhere else.
ORDER_TYPES: dict[str, list[dict[str, str]]] = {
    "Order": [
        {"name": "c", "type": "bytes32"},     # the container commitment
        {"name": "modelId", "type": "uint32"},
        {"name": "slaSecs", "type": "uint32"},
        {"name": "rateIn", "type": "uint128"},
        {"name": "rateOut", "type": "uint128"},
        {"name": "unitsIn", "type": "uint32"},
        {"name": "unitsOut", "type": "uint32"},
        {"name": "designated", "type": "uint32"},
        {"name": "expiresAt", "type": "uint64"},
    ],
}

#: ``Cancel(bytes32 jobId,uint64 issuedAt)`` — the owner's withdrawal, on the
#: JobRegistry's domain. Signature-only: there is no ``cancelFor`` and the
#: contract never reads ``msg.sender``, so this signature is the whole authority
#: and the relaying node cannot author one.
CANCEL_TYPES: dict[str, list[dict[str, str]]] = {
    "Cancel": [
        {"name": "jobId", "type": "bytes32"},
        {"name": "issuedAt", "type": "uint64"},
    ],
}

#: The fixed message a wallet signs to derive its result cipher (spec D11).
DERIVATION_MESSAGE = "VORQ-ENC-V1"

#: Version tag of the sealed plaintext envelope ``{v, owner, result_key, input}``.
ENVELOPE_VERSION = "vorq-env-v1"

SESSION_TYPES: dict[str, list[dict[str, str]]] = {
    "VorqSession": [
        {"name": "address", "type": "address"},
        {"name": "nonce", "type": "string"},
    ]
}

# -- payment authorization -------------------------------------------------------
#
# The escrow payment is EIP-3009 `ReceiveWithAuthorization` under the payment token's own
# domain. Only the payee — the JobRegistry — can execute it. `nonce` is the job id, which
# makes it single-use on the token and binds it to the one job it funds; `validBefore` is
# `expires_at + 1` because the token requires `now < validBefore` and a claim may land
# exactly on `expires_at`.

RECEIVE_AUTHORIZATION_TYPES: dict[str, list[dict[str, str]]] = {
    "ReceiveWithAuthorization": [
        {"name": "from", "type": "address"},
        {"name": "to", "type": "address"},
        {"name": "value", "type": "uint256"},
        {"name": "validAfter", "type": "uint256"},
        {"name": "validBefore", "type": "uint256"},
        {"name": "nonce", "type": "bytes32"},
    ],
}


def vorq_domain(chain_id: int) -> dict[str, Any]:
    """The off-chain VORQ domain — the session handshake's, and no contract's.

    ``chain_id`` is the deployment's, which ``GET /auth/nonce`` announces as
    ``chain_id``. Version ``1`` against the on-chain artifacts' ``2``, with no
    ``verifyingContract`` at all, keeps a login in a namespace the chain will
    never accept.
    """
    return {"name": DOMAIN_NAME, "version": DOMAIN_VERSION, "chainId": int(chain_id)}


def content_job_id(owner: str, c: bytes | str) -> str:
    """Client-owned job id: ``keccak256(owner20 ‖ c32)``.

    ``c`` is the **container commitment** — ``keccak256(version ‖ seed_wrap ‖
    keccak256(ciphertext))``, computed by :func:`vorq._container.commitment` — and
    it is hashed in as it stands. **There is no inner hash here.** The digest of
    the payload already lives inside ``c``; taking another one would produce an id
    no other party computes, and `tests/vectors/container-v1.json` fails the moment
    one reappears.

    That this is client-computable is load-bearing rather than incidental: it is
    what lets a client whose connection dropped mid-submission ask
    ``GET /v1/jobs/{id}`` whether its job landed, instead of re-uploading the
    container to find out. See ``Client._send_complete``.

    Returned as ``0x``-prefixed hex; accepts ``c`` as raw bytes or ``0x`` hex.
    """
    word = to_bytes(hexstr=c) if isinstance(c, str) else bytes(c)
    if len(word) != 32:
        raise ValueError(f"c must be a 32-byte commitment, got {len(word)} bytes")
    return _to_0x_hex(keccak(to_bytes(hexstr=owner) + word))


#: A 32-byte Curve25519 public key as hex, in either of the two spellings the
#: coordinator serves. Whitespace is not one of them.
_HEX32_RE = re.compile(r"\A(?:0[xX])?[0-9a-fA-F]{64}\Z")


def _bare_hex_key(recipient_public_key: str) -> str:
    """The one spelling nacl's ``HexEncoder`` accepts, from either of the two."""
    if not isinstance(recipient_public_key, str) or not _HEX32_RE.match(recipient_public_key):
        raise ValueError(
            "recipient public key must be a 32-byte Curve25519 key as hex (0x optional)"
        )
    return recipient_public_key.lower().removeprefix("0x")


def seal_to(recipient_public_key: str, data: bytes) -> bytes:
    """Seal ``data`` to a recipient's Curve25519 public key (anonymous sender).

    Only the recipient's public key is needed to write one, and only its secret
    key can open it. The SDK's two uses are the wrap inside a container
    (:func:`vorq._container.seal_seed_to`, which adds the width the layout depends
    on) and the ``vorq-sealed-v1`` result a provider seals back to the wallet's
    result key.

    **Both spellings of a key are accepted, because the protocol serves both.**
    A provider's registry key arrives from ``GET /evm/providers/{id}`` as
    ``0x`` hex — every ``bytes`` column on that wire is — while ``GET /key``
    builds its escrow key by hand and serves it bare. nacl's ``HexEncoder``
    strips no prefix, so the normalization has to happen here, on the one door
    both recipients pass through. Getting this wrong is not a soft failure: the
    prefixed spelling died with ``binascii.Error`` before a byte was posted, and
    a designated order could not be submitted at all.
    """
    box = SealedBox(PublicKey(_bare_hex_key(recipient_public_key).encode(), encoder=HexEncoder))
    return bytes(box.encrypt(data))


def _to_0x_hex(value: bytes) -> str:
    to_0x_hex = getattr(value, "to_0x_hex", None)
    if callable(to_0x_hex):
        return to_0x_hex()
    raw = value.hex()
    return raw if raw.startswith("0x") else "0x" + raw


# -- protocols ------------------------------------------------------------------


@runtime_checkable
class Signer(Protocol):
    """Holds the Inference Wallet Key; signs orders and session nonces locally.

    Every chain-bound method takes the :class:`~vorq._terms.ChainContext`
    explicitly. There is no default deployment and no ambient one: the two VORQ
    domains differ only in ``verifyingContract``, so a signer that guessed would
    produce a signature that recovers to a stranger and is refused by nothing
    until the chain refuses it.
    """

    address: str

    def sign_order_v2(self, terms: OrderTerms, ctx: ChainContext) -> str: ...

    def sign_cancel(self, job_id: str, issued_at: int, ctx: ChainContext) -> str: ...

    def sign_payment_authorization(
        self, *, amount: int, job_id: str, expires_at: int, ctx: ChainContext
    ) -> str: ...

    def sign_nonce(self, nonce: str, chain_id: int) -> str: ...


@runtime_checkable
class Cipher(Protocol):
    """Seals and opens end-to-end payloads."""

    @property
    def public_key(self) -> str: ...

    def encrypt(self, data: bytes) -> bytes: ...

    def decrypt(self, data: bytes) -> bytes: ...


# -- implementations ------------------------------------------------------------


class WalletSigner:
    """EIP-712 signer backed by a secp256k1 wallet key.

    The key is read from ``private_key`` or, failing that, the ``key_env``
    environment variable — so production code keeps the secret out of source.
    Use a dedicated wallet funded with your inference budget, never a main
    wallet's key.
    """

    def __init__(
        self,
        private_key: str | None = None,
        *,
        key_env: str = "VORQ_WALLET_KEY",
    ) -> None:
        key = private_key or os.environ.get(key_env)
        if not key:
            raise ValueError(
                f"no wallet key: pass private_key or set ${key_env}"
            )
        self._account = Account.from_key(key)
        self.address: str = self._account.address

    @classmethod
    def generate(cls) -> "WalletSigner":
        """Create a signer over a freshly generated wallet (tests, ephemeral use)."""
        return cls(Account.create().key.hex())

    def _sign_domain(self, domain: dict, types: dict, message: dict) -> str:
        signed = Account.sign_typed_data(self._account.key, domain, types, message)
        return _to_0x_hex(signed.signature)

    def sign_order_v2(self, terms: "OrderTerms", ctx: "ChainContext") -> str:
        """Sign an order on the JobRegistry's domain. Returns a 0x signature.

        ``c`` is the container commitment — ``keccak256(version ‖ seed_wrap ‖
        keccak256(ciphertext))`` — and it is the only thing on this struct that
        says anything about the payload. The coordinator recomputes it from the
        container bytes that arrive with the funded submission, recovers this
        signature to the paying wallet, and the chain derives the job id as
        ``keccak256(owner ‖ c)``.

        No CID of any kind enters this digest, because the name does not exist
        yet: this client hands bytes to the node and the node mints the name.
        """
        return self._sign_domain(order_domain(ctx), ORDER_TYPES, terms.message())

    def sign_cancel(self, job_id: str, issued_at: int, ctx: "ChainContext") -> str:
        """Sign ``Cancel(jobId, issuedAt)`` on the JobRegistry's domain.

        ``issued_at`` is unix seconds and the chain bounds it to ±600 s. There is
        no nonce: the job's one-shot state machine is the replay guard, because a
        cancelled job cannot be cancelled twice.
        """
        message = {"jobId": to_bytes(hexstr=job_id), "issuedAt": int(issued_at)}
        return self._sign_domain(order_domain(ctx), CANCEL_TYPES, message)

    def sign_payment_authorization(
        self, *, amount: int, job_id: str, expires_at: int, ctx: "ChainContext"
    ) -> str:
        """Sign the escrow payment. Every member but ``amount`` comes from the order and the context.

        ``amount`` is the quote's — ``cap + fee + gas_fee`` — and is what the
        JobRegistry pulls at claim. The payee is the context's own
        ``job_registry`` and only that payee can execute the authorization, so a
        signature that leaked authorizes nobody else.
        """
        message = {
            "from": self.address,
            "to": ctx.job_registry,
            "value": int(amount),
            "validAfter": 0,
            "validBefore": int(expires_at) + 1,
            "nonce": to_bytes(hexstr=job_id),
        }
        return self._sign_domain(payment_domain(ctx), RECEIVE_AUTHORIZATION_TYPES, message)

    def sign_nonce(self, nonce: str, chain_id: int) -> str:
        """Sign a session-handshake nonce under the deployment's chain; returns a 0x EIP-712 signature."""
        message = {"address": self.address, "nonce": nonce}
        return self._sign_domain(vorq_domain(chain_id), SESSION_TYPES, message)


class SealedBoxCipher:
    """libsodium sealed-box cipher over a Curve25519 keypair.

    ``encrypt`` seals to ``recipient_public_key`` (required to encrypt);
    ``decrypt`` opens boxes addressed to this cipher's own key. The private key is
    read from ``private_key`` or the ``key_env`` environment variable.
    """

    def __init__(
        self,
        private_key: str | None = None,
        *,
        recipient_public_key: str | None = None,
        key_env: str = "VORQ_CIPHER_KEY",
    ) -> None:
        key = private_key or os.environ.get(key_env)
        if not key:
            raise ValueError(f"no cipher key: pass private_key or set ${key_env}")
        self._private_hex = key
        self._private = PrivateKey(key.encode(), encoder=HexEncoder)
        # Same normalization as :func:`seal_to`, and for the same reason: a
        # recipient key is a public value that reaches a caller in either
        # spelling, and the two doors that seal to one must not disagree.
        self._recipient = (
            PublicKey(_bare_hex_key(recipient_public_key).encode(), encoder=HexEncoder)
            if recipient_public_key
            else None
        )

    @classmethod
    def generate(cls) -> "SealedBoxCipher":
        """Create a cipher over a freshly generated keypair (tests, ephemeral use)."""
        priv = PrivateKey.generate()
        return cls(priv.encode(HexEncoder).decode())

    @classmethod
    def from_seed(cls, seed: bytes) -> "SealedBoxCipher":
        """Build a cipher from 32 bytes of secret seed material.

        The seed *is* the Curve25519 scalar, so the same seed always yields the
        same keypair — that is what makes :func:`derive_result_cipher` reproducible.
        """
        return cls(PrivateKey(seed[:32]).encode(HexEncoder).decode())

    @property
    def public_key(self) -> str:
        """This cipher's Curve25519 public key as hex — share it to receive."""
        return self._private.public_key.encode(HexEncoder).decode()

    def encrypt(self, data: bytes) -> bytes:
        if self._recipient is None:
            raise ValueError("no recipient_public_key set: nothing to seal to")
        return SealedBox(self._recipient).encrypt(data)

    def decrypt(self, data: bytes) -> bytes:
        return SealedBox(self._private).decrypt(data)


def derive_result_cipher(signer: "WalletSigner") -> "SealedBoxCipher":
    """Wallet-derived result cipher (spec D11): X25519 from ``keccak256`` of a
    deterministic signature over :data:`DERIVATION_MESSAGE`.

    RFC 6979 makes the signature — and therefore the keypair — reproducible from
    the wallet key alone, so the key results are sealed back to survives a restart
    with nothing on disk. Pass an explicit ``cipher=`` instead when the key cannot
    be derived (a contract wallet, a KMS signer) or must be persisted elsewhere.
    """
    sig = Account.sign_message(encode_defunct(text=DERIVATION_MESSAGE), signer._account.key)
    return SealedBoxCipher.from_seed(keccak(bytes(sig.signature)))
